<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseAppHost>false</UseAppHost>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="TrackedFileSystem.cs" />
    <PackageReference Include="Microsoft.Build" Version="17.11.48" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Locator" Version="1.11.2" />
  </ItemGroup>
</Project>
